### ISSUE TITLE
Redirecting blog post to www

### ISSUE THREAD

**Issue by rraue** [mozilla/blogdotmozilladotorg#10]
The last month we run a test to check if the same content of https://blog.mozilla.org/firefox/firefox-64-default-64-bit-windows/ would perform better on www. We set a canonical to www but Google did not pick it up. Nonetheless, the page on www started ranking for similar keywords and has a way higher conversion rate: https://docs.google.com/spreadsheets/d/1DXXcfBLjIidNi5ETqOhdA7h64SU5OGXxydJHTegOylI/edit#gid=490387227

Therefore we want to redirect 301 https://blog.mozilla.org/firefox/firefox-64-default-64-bit-windows/ to https://www.mozilla.org/en-US/firefox/windows-64-bit/ so all rankings of the blogpost are picked up by the page on www and we get a maximised conversion rate.

As the article is en-US only right now the redirect should go to the locale /en-US/ on www as well and not to the locale free redirect.

- [x] redirect blogpost 301 to the page on www

**Comment by craigcook** [comment]
Done.
