### ISSUE TITLE
 Enable feature images to show on the press center blogs

### ISSUE THREAD

**Issue by ejregithub** [mozilla/blogdotmozilladotorg#13]
Original Request - https://trello.com/c/o7BbaE6Q

Description:   Enable feature images to show on the press center blogs. 

Contact Lucile V with questions.

Success Criteria:
- [ ] Enabled before July

**Comment by craigcook** [comment]
There are two different places featured images can appear: on single posts as a big image at the top of the page, and in summaries (like the front page). There are separate settings to enable/disable them so we can show images on one or the other, or neither, or both.

The vast majority of press posts have no images so if we enable them in summaries almost all of them will get default placeholder images, which may not be what we really want. I would probably recommend enabling them for single posts but keeping them off for summaries. 

I can talk to Lucile about the options and find out what she really needs here.

**Comment by craigcook** [comment]
Sorry, I forgot all about this until I happened to be looking in this repo just now...

Any of the options above are trivial to enable, we just need clarification from Lucile on what she wants. I never actually asked her but I'm making a note to myself now to do that so we can cross this off the list.

**Comment by ejregithub** [comment]
@craigcook - I checked the press blog, don't see that either was implemented (as far as I could tell) so I pinged Lucile on this.

**Comment by ejregithub** [comment]
@craigcook - so the want is for images in the single posts (not summaries) - and the real reason is that they hope for those to appear in social posts (Twitter), though I'm not sure if that's what will happen . . . if you can enable it images in single posts, we'll find out.

**Comment by craigcook** [comment]
So just to further clarify, featured images for social media are ALWAYS enabled, you just have to set an image on a given post. All we're enabling/disabling here is whether those images are also displayed on the blog site.

I've enabled the display of featured images for single posts but not in summaries. Most prior posts still don't have any image set so there won't be any immediately visible difference, but going forward if you add a featured image to a post it will appear on the site (and there's still the option to hide it on a post-by-post basis).
