### ISSUE TITLE
Translations missing in Blog 

### ISSUE THREAD

**Issue by Malcfra** [mozilla/blogdotmozilladotorg#15]
![Comment empêcher la lecture automatique des vidéos grâce aux paramètres de contrôle Firefox   Firefox et au delà](https://user-images.githubusercontent.com/52922424/61219557-c488e080-a714-11e9-8746-f3bba158d4e8.png)

Missing translations:
This post is also available in: – Cet article est également disponible en :
Browse fast. Browse free. – Naviguez toujours plus vite.
"En savoir plus sur" should have the primary blog category instead of the placeholder.
@ejregithub

**Comment by craigcook** [comment]
These should be fixed now.

**Comment by Malcfra** [comment]
Great!
