### ISSUE TITLE
Apply Frontierline Wordpress theme to the data blog

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/blogdotmozilladotorg#17]
I'm currently working to revive the https://blog.mozilla.org/data and similar to the request in https://github.com/mozilla/blogdotmozilladotorg/issues/1, I would like to add the Frontierline theme to the blog. I have admin privileges to the blog but it seems that I can't add themes to it. would someone be able to help me out with that?

**Comment by craigcook** [comment]
I've just activated the theme. You can tinker with the theme options and customize it to your liking, and feel free to ping me with any questions (craigcook on slack). Cheers!

**Comment by teonbrooks** [comment]
thanks @craigcook!
