### ISSUE TITLE
Set up EKR presence, author page, on blog.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/blogdotmozilladotorg#18]
Tasks
- [x] Modify author page template to show author name and author icon

MJ to do a mock up and share back to Craig - Mar 26
Craig to assess effort and provide estimate -
Determine priority and when the work can be done

**Comment by craigcook** [comment]
Author archive template added in https://github.com/craigcook/frontierline-theme/commit/c96ea2a9b85de4a70a56c2b11ae1c827126b5c4c and pushed to production: https://blog.mozilla.org/blog/author/ekrmozilla-com/

Adding a redirect to bedrock in https://github.com/mozilla/bedrock/pull/8861
