### ISSUE TITLE
Title contrast issues on berlin blog theme

### ISSUE THREAD

**Issue by alexgibson** [mozilla/blogdotmozilladotorg#3]
I noticed a few different posts on the Mozilla Berlin blog have colour contrast issues, due to the white heading in the top hero section being positioned over the top of hero images.

URLs & screenshots below:

https://blog.mozilla.org/berlin/die-heisseste-waehrung-im-internet-deine-aufmerksamkeit/

![screenshot_2019-02-12 aufmerksamkeitsokonomie warum abkenkung ein milliardengeschaft ist - mozilla](https://user-images.githubusercontent.com/400117/52644198-49f23580-2ed6-11e9-9d2a-fc80806d8eb3.jpg)

https://blog.mozilla.org/berlin/wie-das-internet-beziehungen-neu-erfunden-hat-%e2%9d%a4%ef%b8%8f/

![screenshot_2019-02-12 verandert das internet unsere liebe mozilla podcast about web](https://user-images.githubusercontent.com/400117/52644401-a8b7af00-2ed6-11e9-9996-9bac406e4b7c.jpg)

A quick fix would be to choose different background images for these posts, however this kind of issue is likely to keep coming up given the current design. A better fix may be to tweak the header design so that the title can work on top of any background colour.

**Comment by craigcook** [comment]
This is fixed in https://github.com/craigcook/mozilla-berlin-theme/commit/66f505390172ee5f1d4b23f7a588be007e45947f and pushed to production. I changed the gradient to a solid shaded bar.
